/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gphoto2.h>
#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "globals.h"
#include "interface.h"
#include "support.h"
#include "util.h"
#include "gtkam-tree.h"
#include "gtkam-list.h"

GtkWidget*
create_confirm_window (void)
{
  /* widget labels: "message" "yes" "no" */

  GtkWidget *confirm_window;
  GtkWidget *vbox4;
  GtkWidget *confirm_label;
  GtkWidget *hbox2;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkWidget *hsep;

  confirm_window = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (confirm_window), "confirm_window", confirm_window);
  gtk_window_set_title (GTK_WINDOW (confirm_window), _("gtKam Confirmation"));
  gtk_window_set_position (GTK_WINDOW (confirm_window), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (confirm_window), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (confirm_window), 350, 200);
  gtk_container_set_border_width (GTK_CONTAINER (confirm_window), 5);

  vbox4 = gtk_vbox_new (FALSE, 7);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "vbox", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (confirm_window), vbox4);

  confirm_label = gtk_label_new (_("Are you sure?"));
  gtk_widget_ref (confirm_label);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "message", confirm_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (confirm_label);
  gtk_box_pack_start (GTK_BOX (vbox4), confirm_label, TRUE, TRUE, 0);

  hsep = gtk_hseparator_new();
  gtk_widget_ref (hsep);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "hsep", hsep,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hsep);

  hbox2 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_end (GTK_BOX (vbox4), hbox2, FALSE, TRUE, 0);
  gtk_box_pack_end (GTK_BOX (vbox4), hsep, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 5);

  button19 = gtk_button_new_with_label (_("Yes"));
  gtk_widget_ref (button19);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "yes", button19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button19);
  gtk_box_pack_start (GTK_BOX (hbox2), button19, FALSE, TRUE, 0);

  button20 = gtk_button_new_with_label (_("No"));
  gtk_widget_ref (button20);
  gtk_object_set_data_full (GTK_OBJECT (confirm_window), "no", button20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button20);
  gtk_box_pack_start (GTK_BOX (hbox2), button20, FALSE, TRUE, 0);

  return confirm_window;
}
